apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist
  annotations:
    app.openshift.io/connects-to: database
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/tasklist-cicd'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"tasklist:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image"}]'
    argocd.argoproj.io/sync-wave: "200"
  labels:
    app: tasklist
    app.kubernetes.io/name: server
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: server
    app.openshift.io/runtime: spring
    app.kubernetes.io/part-of: tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tasklist
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasklist
        name: tasklist
    spec:
      containers:
        - name: app
          image: >-
            image-registry.openshift-image-registry.svc:5000/tasklist-dev/tasklist:latest
          ports:
            - containerPort: 8100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9100
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9100
            initialDelaySeconds: 5
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9100
            failureTreshold: 5
            periodSeconds: 15
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: JAVA_OPTS_APPEND
            value: '-DDB_URL=jdbc:postgresql://postgresql:5432/$(POSTGRESQL_DATABASE)?user=$(POSTGRESQL_USER)&password=$(POSTGRESQL_PASSWORD) -DCONFIG_FILE=/opt/config/tasklist.properties'
          - name: JAVA_ARGS
            valueFrom:
              configMapKeyRef:
                name: tasklist-config
                key: JAVA_ARGS
          volumeMounts:
          - name: config-volume
            mountPath: /opt/config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: tasklist-config
            items:
            - key: tasklist.properties
              path: tasklist.properties
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
