kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tasklist-dev-src
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
