apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: tasklist-mesh
  labels:
    app: tasklist
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  mode: MultiTenant
  profiles:
    - default
  gateways:
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
      scrape: true
  version: v2.4
  telemetry:
    type: Istiod
