apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tasklist-dev

resources:
- ../../../components/apps/tasklist/base
- ../../../components/apps/database/base

patchesJson6902:
- target:
    kind: Deployment
    version: apps/v1
    name: tasklist
  path: deployment-patch.yaml