apiVersion: v1
kind: Secret
metadata:
  labels:
    app: tasklist
    app.kubernetes.io/name: tasklist
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: tasklist
    app.kubernetes.io/part-of: tasklist
  name: postgresql
stringData:
  database-name: tasklist
  database-password: 5up3r53cr3t
  database-user: tasklist