apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tasklist-cicd

resources:
- ../../../components/tekton/pipelines/dev-pipeline/base
- ../../../components/tekton/tasks/base
- cm-tasklist-mvn-settings.yaml
