apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: tasklist
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-80
        protocol: HTTP
      hosts:
        - patch.this # override this with cluster values
